### ISSUE TITLE
cannot have anything except "undefined" result

### ISSUE THREAD

**Issue by Aethyn** [gintsgints/sequelize#10]
Hi guys,
Well, first thanks a lot for this oracle support ! That's pretty cool.

I have an issue with requesting, in a first time I had an error "_.contains() is not a function" but I found this (https://github.com/mgonto/restangular/issues/1298) and it's because of a knowed problem with Lodash latest version.
So I just replace all "_.contains" by "_.includes" in the sequelize\node_modules\lodash and it works fine.

But I can't have anything except "undefined" as a query result.
The table model + connectString : 

```
// Oracle official database driver
var oracledb = require('oracledb');
var sequelize = require('sequelize');
var database = new sequelize('(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=)(PORT=))(CONNECT_DATA=(SERVICE_NAME=)))', 'user', 'password',
{
    host: 'localhost',
    dialect: 'oracle',
    quoteIdentifiers: false,
});
```

```
// Sequelize table define
var User = database.define('sequelize_user', {
    id: {
        type: sequelize.INTEGER(15),
        primaryKey: true,
        autoIncrement: true,
    },
    name: {
        type: sequelize.STRING(100),
    },
    ip: {
        type: sequelize.STRING(64),
    },
}, {
    freezeTableName: true,
    timestamps: false,
});

module.exports = User;`
```

And the code : 

```
// This is the official Oracle Database Driver
var oracledb = require('oracledb');
// The table model
var User = require('./sequelize_model.js');

// try a FindAll
var users = User.findAll().then(function(data){
    data.forEach(function (data)
    {
        console.log('User : ');
        console.log(data.id);
    });
});

```

In console I just have "User : undefined" and nothing else...

I tried with data.id, data.dataValues.id, or getData() with a getter in the model (like the standard sequelize), but no difference...
Did I made a mistake ?
Any help is really welcome. Thanks a lot.

**Comment by gintsgints** [comment]
Begin with small test like this:

```
User = sequelize.define('User', {
            email: DataTypes.STRING
            });

User.create({
              email: 'test@sequelizejs.com'
            });

User.findAll({
              order: [sequelize.literal('email = ' + sequelize.escape('test@sequelizejs.com'))]
            }).then(function (users) {
              console.log(users.length);
              users.forEach(function (user) {
                console.log(user.get('email'));
              });
```

**Comment by Aethyn** [comment]
Hi, and thanks for your help,
So I tried your code, first I have :  

`User = database.define('User', {  
    email:sequelize.STRING  
},{  
    timestamps:false,  
    freezeTableName:true  
});`  

And It works. I just changed sequelize.define() to database.define() and DataTypes.STRING to sequelize.STRING (cause he tolds me "DataTypes is not define" and sequelize.define() isn't a function, but I think it's obviously normal). So there is no error here, it works.

Next the create :  
`User.create({  
    email:'test@sequelizejs.com'  
});`  

There is an error here : the query displayed in console is :  
`Auto commit:true Exec: =====  INSERT INTO sequelize_user (email) VALUES ('test@sequelizejs.com') RETURNING "id" INTO :id===== end of code`

But I don't have any id column on this table so I take a big ORA-00904: invalid "id" identifier at Error (native). I can't find how to disable this returning so I added a field "id" with primary key, and then it works. (Sorry, I'm really newbie with Sequelize and GitHub).  

So the define was :  
`User = database.define('sequelize_user',  
{  
    id_record:{  
        type: sequelize.STRING,  
        primaryKey:true,  
    },  
    email:sequelize.STRING  
},{timestamps:false,freezeTableName:true});`  
`
And the query was : 
`Executing (default): INSERT INTO sequelize_user (id_record,email) VALUES (1,'test@sequelizejs.com')`

And it works too (I checked the database and the line was successfully saved).
Then I tried your last code part :  
`User.findAll({  
    order: [sequelize.literal('email = ' + database.escape('test@sequelizejs.com'))]  
}).then(function (users) {  
    console.log(users.length);  
    users.forEach(function (user) {  
        console.log(user.get('email'));  
    });  
});`  

But I encounter a ORA-00933: SQL command not properly ended because of the email equal symbol in "SELECT id_record, email FROM sequelize_user sequelize_user ORDER BY email = 'test@sequelizejs.com'"
And as I didn't really understand what you want to do with this ORDER, I just replaced it by a simple 
WHERE as :
`Executing (default): SELECT id_record, email FROM sequelize_user sequelize_user WHERE sequelize_user.email = 'test@sequelizejs.com'`

I obtained :
`1  
undefined`
 :/

EDIT @ 3:00PM : I just did the same test with mysql and postgres in sequelize, just changing the "dialect" parameter in the code below (I created two base on MySQL and PostGres with the same database name, table name and user) and it works for both of two !
I obtained :
`1  
test@sequelizejs.com`
So I only have this issue with Oracle but its the only one I really need to use...

**Comment by gintsgints** [comment]
Actualy oracle dialect is really in development phase and many unpredicted stuff can come up.

**Comment by Aethyn** [comment]
Ok, so I will continue my efforts and try to see where it doesn't works inside the /lib/dialect/oracle.
I hope I'll find a solution.

**Comment by gintsgints** [comment]
Ok. good. I left issue open. If you find why, attach issue number to pull request.

**Comment by Aethyn** [comment]
One month after, I still not found the answer.
I close the issue and will probably choose the DAO design pattern instead of using an ORM.
I will update this if I come back to the Sequelize-oracle later.
Sorry for the inconvenience and thanks for your help.
