### ISSUE TITLE
Why isn't the oracle dialect imported in lib/data-types?

### ISSUE THREAD

**Issue by kulkarnih** [gintsgints/sequelize#7]
I think the oracle dialect needs to be added [here](https://github.com/gintsgints/sequelize/blob/master/lib/data-types.js#L926).

Currently base-types are invoked [here](https://github.com/gintsgints/sequelize/blob/master/lib/dialects/oracle/data-types.js#L3).
This appears to be wrong. Example for [mysql](https://github.com/gintsgints/sequelize/blob/master/lib/dialects/mysql/data-types.js#L6).

Was this done for testing? If not, I will add it there.

**Comment by gintsgints** [comment]
Could be that mysql variant has been refactored for better code. If you see you can improve, sure. Go on.

**Comment by gintsgints** [comment]
Ok... I see now. They moved lot of specific functions from sql-string to apropriate types.

So oracle should be added to data-types.js

**Comment by kulkarnih** [comment]
Yes. But adding that is increasing the number of failed test cases. I'm also working on defining the data types for oracle.
Some test cases can be fixed by changing the output for Oracle.
